name: Build and Release macOS Tarballs

on:
  push:
    branches: [ "builds" ]

jobs:
  build-and-release:
    runs-on: macos-latest
    strategy:
      matrix:
        os: [macos-latest]
        target: [x86_64-apple-darwin, aarch64-apple-darwin]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install GitHub CLI on macOS
        if: matrix.os == 'macos-latest'
        run: brew install gh

      - name: Set up GitHub CLI authentication
        run: |
          gh auth setup-git

      - name: Run Makefile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make release
